# Massa MCP — Scene & Object management tools
# Query, organise, and inspect Massa objects and console state.

__all__ = ("register",)

from blmcp.tools_helpers.connection import send_code
from mcp.server.fastmcp import FastMCP
from mcp.types import ToolAnnotations


def register(mcp: FastMCP) -> None:

    @mcp.tool(annotations=ToolAnnotations(title="List Massa Objects", readOnlyHint=True))
    def list_massa_objects() -> dict[str, object]:
        """
        Return all objects in the scene that were generated by Massa.

        Each entry shows the object name, the cartridge op_id, location,
        and a condensed MASSA_PARAMS snapshot so you can re-examine or
        rerun them.
        """
        code = """
import bpy
objects = []
for obj in bpy.data.objects:
    op_id = obj.get("massa_op_id", "")
    if not op_id:
        continue
    loc = list(obj.location)
    params = dict(obj.get("MASSA_PARAMS", {}))
    objects.append({
        "name":         obj.name,
        "op_id":        op_id,
        "location":     [round(v, 4) for v in loc],
        "massa_params": params,
    })
result = {"status": "ok", "objects": objects, "count": len(objects)}
"""
        return send_code(code, strict_json=True)

    @mcp.tool(annotations=ToolAnnotations(title="Get Massa Console State", readOnlyHint=True))
    def get_massa_console_state() -> dict[str, object]:
        """
        Return the current Massa console (shared settings) property values.

        The console is the persistent settings brain stored on context.scene.massa_console.
        Useful for inspecting active scale, polish flags, UV settings, and seam solver state.
        """
        code = """
import bpy
scene = bpy.context.scene
console = getattr(scene, "massa_console", None)
if console is None:
    result = {"status": "error", "message": "massa_console not found — is the Massa addon enabled?"}
else:
    props = {}
    for attr in dir(console):
        if attr.startswith("_"): continue
        try:
            val = getattr(console, attr)
            # Only keep simple scalar/string values
            if isinstance(val, (bool, int, float, str)):
                props[attr] = val
        except Exception:
            pass
    result = {"status": "ok", "massa_console": props}
"""
        return send_code(code, strict_json=True)

    @mcp.tool(annotations=ToolAnnotations(title="Set Massa Console Property", destructiveHint=True))
    def set_massa_console_property(property_name: str, value: bool | int | float | str) -> dict[str, object]:
        """
        Set a property on the Massa console (shared settings store).

        property_name — attribute name on context.scene.massa_console
        value         — new value (bool, int, float, or str)

        Use get_massa_console_state to discover available property names.
        """
        value_repr = repr(value)
        code = f"""
import bpy
scene = bpy.context.scene
console = getattr(scene, "massa_console", None)
if console is None:
    result = {{"status": "error", "message": "massa_console not found."}}
elif not hasattr(console, "{property_name}"):
    result = {{"status": "error", "message": "Property '{property_name}' not found on massa_console."}}
else:
    try:
        setattr(console, "{property_name}", {value_repr})
        result = {{"status": "ok", "property": "{property_name}", "value": {value_repr}}}
    except Exception as e:
        result = {{"status": "error", "message": str(e)}}
"""
        return send_code(code, strict_json=True)

    @mcp.tool(annotations=ToolAnnotations(title="Get Object Massa Params", readOnlyHint=True))
    def get_object_massa_params(object_name: str = "") -> dict[str, object]:
        """
        Return the full MASSA_PARAMS snapshot stored on a Massa-generated object.

        This is the complete operator state used by the resurrection/redo system.
        Pass these params back to run_massa_cartridge or rerun_massa_cartridge to
        reproduce or modify the object.

        object_name — target object; uses the active object when empty.
        """
        code = f"""
import bpy
obj_name = "{object_name}"
obj = bpy.data.objects.get(obj_name) if obj_name else bpy.context.active_object
if obj is None:
    result = {{"status": "error", "message": "No object found."}}
elif "MASSA_PARAMS" not in obj:
    result = {{"status": "error", "message": f"Object '{{obj.name}}' has no MASSA_PARAMS."}}
else:
    result = {{
        "status":       "ok",
        "object":       obj.name,
        "op_id":        obj.get("massa_op_id", ""),
        "massa_params": dict(obj["MASSA_PARAMS"]),
    }}
"""
        return send_code(code, strict_json=True)

    @mcp.tool(annotations=ToolAnnotations(title="Align Objects to Grid", destructiveHint=True))
    def align_massa_objects_to_grid(
        object_names: list[str],
        axis: str = "X",
        spacing: float = 2.0,
        origin: list[float] | None = None,
    ) -> dict[str, object]:
        """
        Evenly space a list of objects along an axis — useful for laying out
        generated parts side by side for inspection.

        object_names — list of object names to arrange
        axis         — 'X', 'Y', or 'Z'
        spacing      — distance between object origins
        origin       — [x, y, z] starting position; uses world origin when omitted
        """
        origin_repr = repr(origin or [0.0, 0.0, 0.0])
        code = f"""
import bpy
from mathutils import Vector

names  = {repr(object_names)}
axis   = "{axis}".upper()
step   = {spacing}
origin = Vector({origin_repr})
axis_idx = {{"X": 0, "Y": 1, "Z": 2}}.get(axis, 0)

moved = []
for i, name in enumerate(names):
    obj = bpy.data.objects.get(name)
    if obj is None:
        moved.append({{"name": name, "error": "not found"}})
        continue
    new_loc = origin.copy()
    new_loc[axis_idx] += i * step
    obj.location = new_loc
    moved.append({{"name": obj.name, "location": list(obj.location)}})

result = {{"status": "ok", "axis": axis, "spacing": step, "objects": moved}}
"""
        return send_code(code, strict_json=True)
